pipeline {
    agent {
        node {
        label 'AGENT-1'
        }
    }
    environment {
        appVersion = ''
        REGION = 'us-east-1'
        ACC_ID = '025523569021'
        PROJECT = 'roboshop'
        COMPONENT = 'catalogue'
    }
    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }

    stages{
        stage('init') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1}') {
                        sh """
                            cd 10-sg
                            terraform init -reconfigure
                        """
                    }
                }
            }
        }
        stage('plan') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1}') {
                        sh """
                            cd 10-sg
                            terraform plan
                        """
                    }
                }
            }
        }
        stage('apply') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1}') {
                        sh """
                            cd 10-sg
                            terraform apply -auto-approve
                        """
                    }
                }
            }
        }
        stage('Bastion ACM EKS') {
            parallel {
                stage('apply') {
                    steps {
                        script {
                            withAWS(credentials: 'aws-creds', region: 'us-east-1}') {
                                sh """
                                    cd 20-bastion
                                    terraform apply -auto-approve
                                """
                            }
                        }
                    }
                }
                stage('apply') {
                    steps {
                        script {
                            withAWS(credentials: 'aws-creds', region: 'us-east-1}') {
                                sh """
                                    cd 60-acm
                                    terraform apply -auto-approve
                                """
                            }
                        }
                    }
                }
                stage('apply') {
                    steps {
                        script {
                            withAWS(credentials: 'aws-creds', region: 'us-east-1}') {
                                sh """
                                    cd 80-eks
                                    terraform apply -auto-approve
                                """
                            }
                        }
                    }
                }
            }
        }
        stage('apply') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1}') {
                        sh """
                            cd 70-Ingress-alb
                            terraform apply -auto-approve
                        """
                    }
                }
            }
        }
    }    

    post {
        always {
            echo 'I will always says Hello again!'
            deleteDir()
        }
        success {
            echo 'Hello Success'
        }
        failure {
            echo 'Hello Failure'
        }
    }
}

