pipeline {
    agent {
        node {
        label 'AGENT-1'
        }
    }
    environment {
        appVersion = ''
        REGION = 'us-east-1'
        ACC_ID = '025523569021'
        PROJECT = 'roboshop'
        COMPONENT = 'catalogue'
    }
    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }

    stages{ 
        stage('init') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1}') {
                        sh """
                            cd 20-bastion
                            terraform init -reconfigure
                        """
                    }
                }
            }
        }
        stage('plan') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1}') {
                        sh """
                            cd 20-bastion
                            terraform plan
                        """
                    }
                }
            }
        }
        stage('apply') { 
            input {
                message "Shoule we continue ?"
                ok "Yes, we should."
                submitter "vamsi"
            }
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1}') {
                        sh """
                            cd 20-bastion
                            terraform apply -auto-approve
                        """
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'I will always says Hello again!'
            deleteDir()
        }
        success {
            echo 'Hello Success'
        }
        failure {
            echo 'Hello Failure'
        }
    }
}

